"""initial

Revision ID: e9a759611ce2
Revises: 
Create Date: 2025-10-01 09:27:48.496460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a759611ce2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_id'), 'banks', ['id'], unique=False)
    op.create_index(op.f('ix_banks_slug'), 'banks', ['slug'], unique=True)
    op.create_table('cbu_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'rate_date', name='uq_cbu_rates_code_date')
    )
    op.create_index(op.f('ix_cbu_rates_code'), 'cbu_rates', ['code'], unique=False)
    op.create_index(op.f('ix_cbu_rates_fetched_at'), 'cbu_rates', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_cbu_rates_id'), 'cbu_rates', ['id'], unique=False)
    op.create_index(op.f('ix_cbu_rates_rate_date'), 'cbu_rates', ['rate_date'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_chat_id'), 'dashboards', ['chat_id'], unique=False)
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_dashboards_is_active'), 'dashboards', ['is_active'], unique=False)
    op.create_index(op.f('ix_dashboards_message_id'), 'dashboards', ['message_id'], unique=False)
    op.create_index(op.f('ix_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('tz', sa.String(length=32), nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('bank_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('buy', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sell', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_rates_bank_id'), 'bank_rates', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_rates_code'), 'bank_rates', ['code'], unique=False)
    op.create_index(op.f('ix_bank_rates_fetched_at'), 'bank_rates', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_bank_rates_id'), 'bank_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_rates_id'), table_name='bank_rates')
    op.drop_index(op.f('ix_bank_rates_fetched_at'), table_name='bank_rates')
    op.drop_index(op.f('ix_bank_rates_code'), table_name='bank_rates')
    op.drop_index(op.f('ix_bank_rates_bank_id'), table_name='bank_rates')
    op.drop_table('bank_rates')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dashboards_user_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_message_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_active'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_chat_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_cbu_rates_rate_date'), table_name='cbu_rates')
    op.drop_index(op.f('ix_cbu_rates_id'), table_name='cbu_rates')
    op.drop_index(op.f('ix_cbu_rates_fetched_at'), table_name='cbu_rates')
    op.drop_index(op.f('ix_cbu_rates_code'), table_name='cbu_rates')
    op.drop_table('cbu_rates')
    op.drop_index(op.f('ix_banks_slug'), table_name='banks')
    op.drop_index(op.f('ix_banks_id'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
